### ISSUE TITLE
enable creating schema, user, pass by environment variables

### ISSUE THREAD

**Issue by ravenblackdusk** [thomseno/docker-h2#1]
Correct me if I'm wrong but remote database creation isn't supported with this image so it makes the web console the only way to create a schema, user, pass which makes it unsuitable for automatic tests. I suggest this image would be able to create a schema, user, pass using environment variables(similar to mariadb's MARIADB_DATABASE, MARIADB_USER, MARIADB_PASSWORD). I might be able to provide a PR if you're interested.

**Comment by thomseno** [comment]
Thanks for bringing this up. I was unaware, that H2 changed the behaviour with version 1.4.198 (PR #1726, #1580). I will have a look into it.

**Comment by thomseno** [comment]
I could restore the pre 1.4.198 functionality by starting the database in server mode and adding `-ifNotExists` to the starting parameters. Then the database will be created on connection if it does not exist.

**Comment by thomseno** [comment]
Republished Docker image with tag 1.4.200 (which corresponds to the H2 version)
